const express = require('express')
const Router = express.Router()
const reviewController = require('../Controllers/reviewController')
const authController = require('../Controllers/authController')

Router.route('/:productId')
    .get(authController.protect,reviewController.getProductReviews)
    .post(authController.protect,reviewController.writeProductReview)
    .patch(authController.protect,reviewController.updateProductReview)
    .delete(authController.protect,reviewController.deleteProductReview)
Router.route('/exists/:productId')
    .get(authController.protect,reviewController.doesReviewExists)
Router.route('/userReview/:productId')
    .get(authController.protect,reviewController.getProductReviewByUser)
module.exports = Router